### ISSUE TITLE
Xcode13 can't not 

### ISSUE THREAD

**Issue by IrisMo** [NordicSemiconductor/IOS-DFU-Library#454]
**Information**
It can be used normally before. When I upgraded to big sur 11.6, xcode13, the SDK will report the following error when compiling, and the demo of the mac version can be reproduced. Will you be able to adapt later? Or what can I do to avoid this situation? Hope to get your reply, thank you!

<img width="1045" alt="wecom-temp-81b84271485d47a9e92d8a53e23b7567" src="https://user-images.githubusercontent.com/29603295/133870992-2a467607-d46a-41ea-a213-ef09b47eed4c.png">

**Comment by dinesharjani** [comment]
Thanks for bringing this up @IrisMo - we just merged a fix to the develop branch: https://github.com/NordicSemiconductor/IOS-DFU-Library/pull/455

Try it out when you can.

**Comment by stami-fb** [comment]
@philips77 @dinesharjani can we get a Cocoapods release from this Xcode 13 compatible version, please? 🙏 

I'm using react-native-nordic-dfu which has this repo as its Cocoapods spec dependency, and those cannot be pointed to a git branch (because of how Cocoapods works). ☹️  So this is preventing anyone from using that on Xcode 13 right now...

**Comment by stami-fb** [comment]
For those ending up here with the same problem, I am able to temporarily work around this issue by removing/commenting out the spec dependency from react-native-nordic-dfu podspec
```
# s.dependency 'iOSDFULibrary', '~> 4.7.1'
```

and adding direct dependency to my main app's Podfile to this develop branch:
```
pod 'iOSDFULibrary', :git => 'https://github.com/NordicSemiconductor/IOS-DFU-Library.git', :branch => 'develop'
```

**Comment by philips77** [comment]
I'll do this tomorrow.

**Comment by abolbis** [comment]
@philips77 @dinesharjani has this fix been released for cocoapods? I still cannot build on xcode 13 for iOS. Getting similar errors
![image](https://user-images.githubusercontent.com/970119/136068289-2c7c2c13-96fb-4253-af26-3ae3f82e6117.png)

**Comment by sofiaschn** [comment]
> @philips77 @dinesharjani has this fix been released for cocoapods? I still cannot build on xcode 13 for iOS. Getting similar errors ![image](https://user-images.githubusercontent.com/970119/136068289-2c7c2c13-96fb-4253-af26-3ae3f82e6117.png)

I am also having the same problem. The way i fixed it, at least until the fixes get to Cocoapods, is by replacing the library's folder (Pods/IOSDFULibrary) with a clone from the develop branch (make sure the names match). Then, run 'pod install' and it should work for now.

@philips77 @dinesharjani, if possible, can you update the main branch with the fixes? Thanks!

**Comment by philips77** [comment]
I'm on it!

**Comment by philips77** [comment]
Fix released in 4.11.1.
